spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            # example:
#            - id: book-service
#              uri: lb://book-service
#              predicates:
#                - Path=${prefix}/books/**
#              filters:
#                - RewritePath=${prefix}/books/(?<segment>.*), /${segment}
#
#            # Swagger Docs of Book Service
#            - id: book-service-docs
#              uri: lb://book-service
#              predicates:
#                - Path=${prefix}/v3/api-docs
#              filters:
#                - RewritePath=${prefix}/(?<segment>.*), /${segment}
    compatibility-verifier:
      enabled: true
server:
  port: 8080
springdoc:
  api-docs:
      enabled: true
      path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
# example:
#      - name: book-service
#        url: /v3/api-docs
#prefix: /v1/api
