spring:
  application:
    name: EurekaServer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/, http://library:9002/eureka
  instance:
    hostname: library
server:
  port: 9002