# CI for Java Microservice application
name: Java Microservice CI/CD

on:
  push:
    branches: [
      "main", "dev",
      "feat/**", "refactor/**",
      "style/**", "fix/**"
    ]
  pull_request:
    branches:
      - dev

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List services
        id: set-matrix
        run: |
          services=$(ls -d src/service/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$services" >> $GITHUB_OUTPUT
  spring-boot-build:
    runs-on: ubuntu-latest
    needs: [detect-services]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect-services.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '21'
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
        working-directory: src/service/${{matrix.service}}

      - name: Build spring boot
        run: ./mvnw clean package -DskipTests
        working-directory: src/service/${{matrix.service}}

      - name: Run Spring boot tests
        run: ./mvnw test
        working-directory: src/service/${{matrix.service}}

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.service}}-jar
          path: src/services/${{matrix.service}}/target/*.jar